# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit boundHTS.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(boundHTS)
library(kableExtra)

devtools::load_all()


## ----sim_poisson_setup, fig.cap="The two-level hierarchical set up of the Poisson simulation. The four child nodes (A, B, C, D) aggregate to the parent node, Total."----
knitr::include_graphics("figures/sim_node_hierarchy.pdf")


## ----glm-helper, include=FALSE------------------------------------------------

rolling_poisson_glm <- function(sim_data, test_indices, series_names) {
  
  lambda_list  <- vector("list", length(test_indices))
  fitted_list  <- vector("list", length(test_indices))
  model_list   <- vector("list", length(test_indices))
  
  for (t in seq_along(test_indices)) {
    
    train_idx <- seq_len(test_indices[t] - 1)
    
    fits <- lambda_est <- matrix(NA, nrow = test_indices[t], ncol = length(series_names))
    colnames(fits) <- colnames(lambda_est) <- series_names
    
    models_t <- list()
    
    for (series in series_names) {
      
      fit <- stats::glm(
        stats::as.formula(paste(series, "~ X + I(X^2)")),
        data   = sim_data[train_idx, c("X", series)],
        family = "poisson"
      )
      
      lambda_est[, series] <- stats::predict(
        fit,
        newdata = sim_data[seq_len(test_indices[t]), c("X", series)],
        type = "response"
      )
      
      fits[, series] <- stats::rpois(
        n = test_indices[t],
        lambda = lambda_est[, series]
      )
      
      models_t[[series]] <- fit
    }
    
    lambda_list[[t]] <- lambda_est
    fitted_list[[t]] <- fits
    model_list[[t]] <- models_t
  }
  
  list(
    models  = model_list,
    lambda  = lambda_list,
    fitted  = fitted_list
  )
}



## ----set up, echo=TRUE--------------------------------------------------------
N <- nrow(boundHTS::poisson_sim_data) 
test_indices  <- seq(from = N - 49, to = N)

glm_results <- rolling_poisson_glm(sim_data = poisson_sim_data,
                                   test_indices =  c(N-49):N,
                                   series_names = c("Tot", "AA", "AB", "BA", "BB"))



## ----pois_tilt, echo=TRUE-----------------------------------------------------

bottom_series <- c("AA", "AB", "BA", "BB")
top_y_vals <- seq(from = 0, to = max(poisson_sim_data$Tot)+10)
n_support <- length(top_y_vals)
n_series  <- length(bottom_series) + 1  # top + bottom

f_tilde_exp <- vector("list", length(test_indices))
nu_exp      <- vector("list", length(test_indices))

for (i in seq_along(test_indices)) {

  t_idx <- test_indices[i]

  # Extract predictive means at time t
  lambda_mat <- glm_results$lambda[[i]]
  lambda_t   <- lambda_mat[t_idx, ]

  lambda_bottom <- lambda_t[bottom_series]
  
  # convolution of bottom series
  lambda_top    <- sum(lambda_bottom) 
  lambda_vec <- c(Total = lambda_top, lambda_bottom)

  ## Allocate storage
  f_tilt <- matrix(0, nrow = n_support, ncol = n_series)
  nu_vec <- numeric(n_series)

  # Construct tilted PMFs
  for (k in seq_along(lambda_vec)) {
    
    # Get PMF of convoluted top series
    base_pmf <- stats::dpois(top_y_vals, lambda_vec[k])
    
    # Find tilting parameter
    nu_k <- stats::uniroot(
      moment_condition_tilting,
      interval  = c(-1, 1),
      f_y       = base_pmf,
      y_vals    = top_y_vals,
      mu_theory = lambda_t[k]
    )$root
    
    # Save tilting parameter
    nu_vec[k] <- nu_k
        
    # Tilt convoluted density towards predictive mean of top series
    f_tilt[, k] <- tilted_density_discrete(
      nu = nu_k,
      f_y = base_pmf,
      y_vals = top_y_vals
    )
  }

  colnames(f_tilt) <- names(lambda_vec)

  f_tilde_exp[[i]] <- f_tilt
  nu_exp[[i]]      <- nu_vec
}



## ----poisson-tilted-plot------------------------------------------------------
t=50
df_plot <- data.frame(
  y     = rep(top_y_vals, ncol(f_tilde_exp[[t]])),
  pmf   = as.vector(f_tilde_exp[[t]]),
  node  = rep(colnames(f_tilde_exp[[t]]), each = length(top_y_vals))
)

means_df <- data.frame(
  node = names(lambda_vec),
  mean = lambda_vec
)

ggplot(df_plot, aes(x = y, y = pmf)) +
  geom_line() +
  geom_vline(data = means_df,
             aes(xintercept = mean),
             linetype = "dashed") +
  facet_grid(~ node) +
  labs(x = "Counts",
       y = "Tilted probability mass")




