# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit boundHTS.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(boundHTS)
library(kableExtra)



## ----sim_poisson_setup, fig.cap="The two-level hierarchical set up of the Poisson simulation. The four child nodes (A, B, C, D) aggregate to the parent node, Total."----
knitr::include_graphics("figures/sim_node_hierarchy.pdf")


## ----glm-helper, include=FALSE------------------------------------------------
rolling_poisson_glm <- function(sim_data, test_indices, series_names) {
  
  lambda_list  <- vector("list", length(test_indices))
  fitted_list  <- vector("list", length(test_indices))
  model_list   <- vector("list", length(test_indices))
  
  for (t in seq_along(test_indices)) {
    
    train_idx <- seq_len(test_indices[t] - 1)
    
    fits <- lambda_est <- matrix(NA, nrow = test_indices[t], ncol = length(series_names))
    colnames(fits) <- colnames(lambda_est) <- series_names
    
    models_t <- list()
    
    for (series in series_names) {
      
      fit <- stats::glm(
        stats::as.formula(paste(series, "~ X + I(X^2)")),
        data   = sim_data[train_idx, c("X", series)],
        family = "poisson"
      )
      # In-sample fitted Poisson means
      lambda_est[train_idx, series] <- fit$fitted.values
      
      # One-step-ahead Poisson mean
      lambda_est[test_indices[t], series] <-
      stats::predict(fit, newdata = sim_data[test_indices[t], c("X", series)])

    # Draw predictive samples from Poisson distribution
    fits[, series] <- stats::rpois(
      n = test_indices[t],
      lambda = lambda_est[, series]
    )
      
      fits[, series] <- stats::rpois(
        n = test_indices[t],
        lambda = lambda_est[, series]
      )
      
      models_t[[series]] <- fit
    }
    
    lambda_list[[t]] <- lambda_est
    fitted_list[[t]] <- fits
    model_list[[t]] <- models_t
  }
  
  list(
    models  = model_list,
    lambda  = lambda_list,
    fitted  = fitted_list
  )
}



## ----set up, echo=TRUE--------------------------------------------------------
N <- nrow(boundHTS::poisson_sim_data) 
test_indices  <- seq(from = N - 49, to = N)

glm_results <- rolling_poisson_glm(sim_data = poisson_sim_data,
                                   test_indices =  c(N-49):N,
                                   series_names = c("Tot", "AA", "AB", "BA", "BB"))



## ----pois_tilt, echo=TRUE-----------------------------------------------------

bottom_series <- c("AA", "AB", "BA", "BB")
top_y_vals <- seq(from = 0, to = max(poisson_sim_data$Tot)+10)
n_support <- length(top_y_vals)
n_series  <- length(bottom_series) + 1  # top + bottom

f_tilde_exp <- vector("list", length(test_indices))
nu_exp <- vector("list", length(test_indices))

for (i in seq_along(test_indices)) {

  t_idx <- test_indices[i]

  # Extract predictive means at time t
  lambda_mat <- glm_results$lambda[[i]]
  lambda_t   <- lambda_mat[t_idx, ]

  lambda_bottom <- lambda_t[bottom_series]
  
  # convolution of bottom series
  lambda_top <- sum(lambda_bottom) 
  lambda_vec <- c(Total = lambda_top, lambda_bottom)

  ## Allocate storage
  f_tilt <- matrix(0, nrow = n_support, ncol = n_series)
  nu_star <- numeric(n_series)

  for(k in 1:length(lambda_vec)) {
    # Convolution step
    f_y <- stats::dpois(top_y_vals, lambda_vec[k]) # density of convolution
    
    # Tilt density
    tilted_dens <- tilt_density(lambda_t[k], top_y_vals, f_y, discrete=TRUE) 
  
    f_tilt[,k] <- tilted_dens$f_tilted # tilted density
    nu_star <- c(tilted_dens$nu_star, nu_star) # tilting parameter
  }
  colnames(f_tilt) <- colnames(lambda_mat)
  f_tilde_exp[[i]] <- f_tilt
  nu_exp[[i]] <- nu_star
}



## ----poisson-tilted-plot------------------------------------------------------
t=50

# Extract predictive means at time t
lambda_mat <- glm_results$lambda[[t]]
lambda_t   <- lambda_mat[nrow(lambda_mat), ]

lambda_bottom <- lambda_t[bottom_series]
  
# density of convolution 
conv_top_dens <- dpois(top_y_vals, sum(lambda_bottom))

conv_plot <- data.frame(
   y = top_y_vals,
   pmf = conv_top_dens,
   node = "Total"
)

# tilted density
df_plot <- data.frame(
  y = rep(top_y_vals, ncol(f_tilde_exp[[t]])),
  pmf = as.vector(f_tilde_exp[[t]]),
  node = rep(colnames(f_tilde_exp[[t]]), each = length(top_y_vals))) %>% 
  mutate(node = ifelse(node=="Tot", "Total", node))

means_df <- data.frame(
  node = names(lambda_t),
  mean = lambda_t
  ) %>% mutate(node = ifelse(node=="Tot", "Total", node))
  

ggplot() +
  geom_line(data = df_plot, aes(x = y, y = pmf, col='Tilted density')) +
  geom_line(data = conv_plot, aes(x = y, y = pmf, col='Convoluted denisty')) +
  geom_vline(data = means_df,
             aes(xintercept = mean, linetype = "Predicitive mean")) +
  facet_wrap(~ node, nrow=5) +
  scale_colour_brewer(palette="Set1") +
  labs(x = "Counts",
       y = "Tilted probability mass")




